import DefaultLayout from "@/components/Layouts/DefaultLayout";
import { ReportStoreProvider } from "@/providers/report-store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
      <ReportStoreProvider>
        <DefaultLayout>{children}</DefaultLayout>
      </ReportStoreProvider>
    </>
  );
}
