import DefaultLayout from "@/components/Layouts/DefaultLayout";
import { UserStoreProvider } from "@/providers/user-store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
      <UserStoreProvider>
        <DefaultLayout>{children}</DefaultLayout>
      </UserStoreProvider>
    </>
  );
}
