import AppFooter from "@/components/app-footer/app-footer";
import AppNavbar from "@/components/app-navbar/app-navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <>
      <AppNavbar />
      {children}
      <AppFooter />
    </>
  );
}
