import DefaultLayout from "@/components/Layouts/DefaultLayout";
import { ImageStoreProvider } from "@/providers/image-store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
      <ImageStoreProvider>
        <DefaultLayout>{children}</DefaultLayout>
      </ImageStoreProvider>
    </>
  );
}
