import AppSidebar from "@/components/app-navbar/app-sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
      <AppSidebar />
      {children}
      
    </>
  );
}
