import DefaultLayout from "@/components/Layouts/DefaultLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
        <DefaultLayout>{children}</DefaultLayout>
    </>
  );
}
