import DefaultLayout from "@/components/Layouts/DefaultLayout";
import { TestStoreProvider } from "@/providers/test-store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function StudentRootLayout({ children }) {
  return (
    <>
      <TestStoreProvider>
        <DefaultLayout>{children}</DefaultLayout>
      </TestStoreProvider>
    </>
  );
}
